---
title: "Twitter, Google Trends, and Polling Data in the 2020 Democratic Primary"
author: "Zoe Padgett and Fatou Thiam"
date: "12/7/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(gtrendsR)
library(dplyr)
library(ggplot2)
library(ggmap)
library(readxl)
library(shiny)
library(rtweet)
library(tidytext)
library(stringr)
library(lubridate)
library(quanteda)
library(SentimentAnalysis)
library(GGally)
library(repmis)
library(httr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#USE THIS CHUNK TO BRING IN interest_over_time_all
source_data("https://github.com/znpadgett/surv727_padgett_thiam/blob/master/Data/interest_over_time_all.RData?raw=true")
```

```{r, include=FALSE}
polling_data %>%
  group_by(Candidate, Pre_post) %>%
  ggplot() +
    geom_col(mapping = aes(x=reorder(Candidate, -Percentage), y=Percentage, fill=Pre_post), color="black",   position="dodge")
```

```{r, include=FALSE}
#USE THIS CHUNK TO BRING IN pre_sent_pos and post_sent_pos
source_data("https://github.com/znpadgett/surv727_padgett_thiam/blob/master/Data/post_sent_pos.RData?raw=true")
source_data("https://github.com/znpadgett/surv727_padgett_thiam/blob/master/Data/pre_sent_pos.RData?raw=true")
```

```{r, tidy=TRUE, warning=FALSE, message=FALSE, include=FALSE}
#clean data
gtrends <-
  interest_over_time_all %>%
  mutate(Candidate=keyword, Data="GTrends") %>%
  group_by(Candidate, Pre_post, Data) %>%
  summarise(Percentage=mean(hits))

poll <-
  polling_data %>%
  select(Candidate, Pre_post, Percentage) %>%
  mutate(Data="Polling") %>%
  group_by(Candidate, Pre_post, Data)

twitter_data <- data.frame("Candidate" = c("Joe Biden", "Bernie Sanders", "Elizabeth Warren", 
                                           "Kamala Harris", "Pete Buttigieg", "Joe Biden", 
                                           "Bernie Sanders", "Elizabeth Warren", "Kamala Harris", 
                                           "Pete Buttigieg"),                            
                           "Pre_post" =c("Pre-debate","Pre-debate","Pre-debate","Pre-debate","Pre-debate",                            "Post-debate","Post-debate","Post-debate","Post-debate","Post-debate"),
                   "Data" = c("Twitter", "Twitter","Twitter","Twitter","Twitter",
                              "Twitter","Twitter","Twitter","Twitter","Twitter"), 
                  "Percentage"=c(pre_sent_pos$Positive[1],pre_sent_pos$Positive[2],
                              pre_sent_pos$Positive[3],pre_sent_pos$Positive[4],
                              pre_sent_pos$Positive[5],post_sent_pos$Positive[1],
                              post_sent_pos$Positive[2],post_sent_pos$Positive[3],
                              post_sent_pos$Positive[4],post_sent_pos$Positive[5]))

twitter <- as_tibble(twitter_data)
twitter <-
  twitter %>%
  group_by(Candidate, Pre_post, Data) %>%
  mutate(Percentage=Percentage*100)

all_data <- rbind(poll, gtrends, twitter)
```

```{r, include=FALSE}
# Define UI
ui <- fluidPage(
  
  # Application title
  titlePanel("2020 Democratic Primary Candidate Data"),
  
  # Sidebar with a dropdown
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "Candidate",                   
                  label = "Candidate",                  
                  choices = c("Joe Biden", "Pete Buttigieg", "Kamala Harris", "Bernie Sanders", "Elizabeth Warren"),                   
                  selected = "Joe Biden"),
      selectInput(inputId = "Data",
                  label = "Data Type",
                  choices = c("Polling", "GTrends", "Twitter"),
                  selected = "Polling")
    ),
    
    # Show plot
    mainPanel(
      plotOutput(outputId = "graph")      
    )
  )
)

# Define server logic
server <- function(input, output) {
  
  output$graph <- renderPlot({
    all_data %>%
      filter(Candidate == input$Candidate, Data == input$Data) %>%
      ggplot() +
      geom_col(mapping = aes(x=Pre_post, y=Percentage, fill=input$Candidate)) +
      ylim(0,100)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)

```
